---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: ahmed1889
    password: Esprit2k171889
     
- name: Tag and push to docker hub
  community.docker.docker_image:
     name: devops:latest
     repository: ahmed1889/cd-project:1.2
     push: yes
     source: local
